---

- name: Install mandatory packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ lp_vg_packages }}"

- name: "Git clone repo to {{ lp_vg_path }}"
  git:
    repo: https://github.com/vgallissot/lp-vg.git
    dest: "{{ lp_vg_path }}"
    update: no # needed for idempotency if files are modified by next task

# Assuming liquidprompt is already installed
- name: "replace repo's generic values by role's pref"
  replace:
    path: "{{ lp_vg_path }}/liquidpromptrc"
    regexp: '^(.*)/usr/local/src/lp-vg/(.*)$'
    replace: "\\1{{ lp_vg_path }}/\\2"
  when: "lp_vg_path != '/usr/local/src/lp-vg'"

- name: "link {{ lp_vg_lprc }} to {{ lp_vg_path }}"
  file:
    src: "{{ lp_vg_path }}/liquidpromptrc"
    dest: "{{ lp_vg_lprc }}"
    state: link
